"""Generate the NVIDIA-side contract artifacts from the shared model contract.

The DeepStream parser previously hardcoded a 3-class / 7-channel tensor while the
qualified Hansung artifact is 10-class / 14-channel. Rather than maintain two
interpretations, everything the parser embeds is generated from
`shared/model_contract.py`:

    edge/pipeline/deepstream/visionops_contract.h   compiled into parser.cpp
    edge/pipeline/deepstream/visionops_contract.json  static-consistency source
    edge/pipeline/deepstream/nvinfer.txt            nvinfer class count and thresholds

`scripts/verify_model_contract.py` re-runs this generator and fails if the files
on disk disagree with the canonical contract.
"""
import argparse
import json
from pathlib import Path

from shared import model_contract

HEADER = """// GENERATED by scripts/gen_deepstream_contract.py -- do not edit by hand.
// Source of truth: shared/model_contract.py (profile: {profile}).
// Canonical mapping version: {mapping_version}
#pragma once

#define VISIONOPS_CONTRACT_PROFILE "{profile}"
#define VISIONOPS_MAPPING_VERSION "{mapping_version}"
#define VISIONOPS_SOURCE_COUNT {source_count}
#define VISIONOPS_CANONICAL_CLASS_COUNT {canonical_count}
#define VISIONOPS_RAW_CHANNELS {channels}
#define VISIONOPS_BOX_VALUES 4
#define VISIONOPS_MAPPED_COUNT {mapped_count}
#define VISIONOPS_SCORE_THRESHOLD {score_threshold}f
#define VISIONOPS_NMS_IOU {nms_iou}f

#define VISIONOPS_CANONICAL_PERSON 0
#define VISIONOPS_CANONICAL_HELMET 1
#define VISIONOPS_CANONICAL_NO_HELMET 2

static const int VISIONOPS_MAPPED_SOURCE_INDEX[VISIONOPS_MAPPED_COUNT] = {{{mapped_sources}}};
static const int VISIONOPS_MAPPED_CANONICAL_ID[VISIONOPS_MAPPED_COUNT] = {{{mapped_canonical}}};
"""

NVINFER = """# GENERATED by scripts/gen_deepstream_contract.py -- do not edit by hand.
# BLOCKED BY HARDWARE: no NVIDIA device, driver, CUDA, TensorRT or DeepStream
# exists in the development environment. Engine generation and parity validation
# must run on a qualified NVIDIA host (see docs/JETSON_DEPLOYMENT_TARGET.md).
[property]
gpu-id=0
net-scale-factor=0.00392156862745098
model-color-format=0
onnx-file=/artifacts/model.onnx
model-engine-file=/artifacts/model-fp16.engine
batch-size=1
network-mode=2
# Full source score head ({source_count} classes), never the canonical subset.
num-detected-classes={source_count}
interval=0
gie-unique-id=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
symmetric-padding=1
parse-bbox-func-name=NvDsInferParseVisionOps
custom-lib-path=/opt/visionops/libvisionops-parser.so
[class-attrs-all]
pre-cluster-threshold={score_threshold}
nms-iou-threshold={nms_iou}
topk=200
"""


def contract_json(contract):
    return {'profile': contract.profile, 'mapping_version': model_contract.mapping_version(contract),
            'source_count': contract.source_count, 'raw_channels': contract.channels,
            'canonical_class_count': contract.canonical_count,
            'source_index_to_canonical': {str(k): v for k, v in sorted(contract.mapping.items())},
            'mapped_source_index': list(contract.sources),
            'mapped_canonical_id': [contract.mapping[s] for s in contract.sources],
            'score_threshold': contract.score_threshold, 'nms_iou': contract.nms_iou,
            'input_shape': list(contract.input_shape)}


def render(contract):
    header = HEADER.format(profile=contract.profile,
                           mapping_version=model_contract.mapping_version(contract),
                           source_count=contract.source_count,
                           canonical_count=contract.canonical_count,
                           channels=contract.channels,
                           mapped_count=len(contract.sources),
                           score_threshold=contract.score_threshold,
                           nms_iou=contract.nms_iou,
                           mapped_sources=', '.join(str(s) for s in contract.sources),
                           mapped_canonical=', '.join(str(contract.mapping[s]) for s in contract.sources))
    nvinfer = NVINFER.format(source_count=contract.source_count,
                             score_threshold=contract.score_threshold, nms_iou=contract.nms_iou)
    return header, nvinfer


def write(folder, contract, check=False):
    folder = Path(folder)
    header, nvinfer = render(contract)
    payload = json.dumps(contract_json(contract), indent=2, sort_keys=True) + '\n'
    files = {'visionops_contract.h': header, 'nvinfer.txt': nvinfer, 'visionops_contract.json': payload}
    changed = []
    for name, content in files.items():
        path = folder / name
        if not path.exists() or path.read_text() != content:
            changed.append(name)
            if not check:
                path.write_text(content)
    return changed


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--profile', default=model_contract.HANSUNG_PPE_10.profile)
    parser.add_argument('--folder', default='edge/pipeline/deepstream')
    parser.add_argument('--check', action='store_true', help='fail if files are stale instead of writing')
    arguments = parser.parse_args()
    contract = model_contract.profile(arguments.profile)
    changed = write(arguments.folder, contract, check=arguments.check)
    if arguments.check and changed:
        raise SystemExit('stale generated DeepStream artifacts: ' + ', '.join(changed))
    print(json.dumps({'profile': contract.profile, 'mapping_version': model_contract.mapping_version(contract),
                      'source_count': contract.source_count, 'raw_channels': contract.channels,
                      'changed': changed}, indent=2))
