// GENERATED by scripts/gen_deepstream_contract.py -- do not edit by hand.
// Source of truth: shared/model_contract.py (profile: hansung_ppe_yolov8n_10).
// Canonical mapping version: hansung_ppe_yolov8n_10@0be69c90227d20ba
#pragma once

#define VISIONOPS_CONTRACT_PROFILE "hansung_ppe_yolov8n_10"
#define VISIONOPS_MAPPING_VERSION "hansung_ppe_yolov8n_10@0be69c90227d20ba"
#define VISIONOPS_SOURCE_COUNT 10
#define VISIONOPS_CANONICAL_CLASS_COUNT 3
#define VISIONOPS_RAW_CHANNELS 14
#define VISIONOPS_BOX_VALUES 4
#define VISIONOPS_MAPPED_COUNT 3
#define VISIONOPS_SCORE_THRESHOLD 0.35f
#define VISIONOPS_NMS_IOU 0.5f

#define VISIONOPS_CANONICAL_PERSON 0
#define VISIONOPS_CANONICAL_HELMET 1
#define VISIONOPS_CANONICAL_NO_HELMET 2

static const int VISIONOPS_MAPPED_SOURCE_INDEX[VISIONOPS_MAPPED_COUNT] = {0, 2, 5};
static const int VISIONOPS_MAPPED_CANONICAL_ID[VISIONOPS_MAPPED_COUNT] = {1, 2, 0};
